schemas:
  bootstrap: 8000
  fairy_tale: 8000
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: /fairy_tale/web/themes/custom/fairy_tale/favicon.ico
  use_default: 1
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: ''
  url: ''
  use_default: 1
table_responsive: '-1'
cdn_provider: jsdelivr
cdn_theme: bootstrap
cdn_cache_ttl_versions: '0'
cdn_cache_ttl_themes: '0'
cdn_cache_ttl_assets: '0'
cdn_cache_ttl_library: '0'
reset: 'Reset Broken Cache'
apply: Apply
reset_http_request_cache: ''
table: ''
