_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 3ca4633f-cbcd-46be-97d3-56c7781296f6
name: 'Fairy tale'
mail: tsaturyan.narine9@gmail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/13
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
